// <auto-generated />
namespace AspNetMvcBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class PostCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201411210249286_PostCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
